In [1]:
import numpy as np

#### Arithmetic with NumPy Arrays

vectorization - batch operations on data

In [3]:
# any arithmetic operations between equal-size arrays applies the operation element-wise
arr = np.array([[1., 2., 3.], [4., 5., 6.]]); arr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [4]:
arr*arr

array([[  1.,   4.,   9.],
       [ 16.,  25.,  36.]])

In [5]:
arr-arr

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [6]:
# Arithmetic operations with scalars propagate the scalar argument to each element in the array
1 / arr

array([[ 1.        ,  0.5       ,  0.33333333],
       [ 0.25      ,  0.2       ,  0.16666667]])

In [7]:
arr*0.5

array([[ 0.5,  1. ,  1.5],
       [ 2. ,  2.5,  3. ]])

In [9]:
# Comparisons between arrays of the same size yield boolean arrays
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]]); arr2

array([[  0.,   4.,   1.],
       [  7.,   2.,  12.]])

In [10]:
arr > arr2

array([[ True, False,  True],
       [False,  True, False]], dtype=bool)

#### Indexing

In [13]:
arr = np.arange(10); arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
arr[0:5]

array([0, 1, 2, 3, 4])

propagation (broadcasting) of a value to a value to a slice

In [20]:
arr[5:-1]=8; arr

array([0, 1, 2, 3, 4, 8, 8, 8, 8, 9])

NB! array slices are views on the original array, i.e. data is not copied, and any modifications to the view will be reflected in the source array

In [24]:
arr_slice = arr[3:7]; arr_slice

array([3, 4, 8, 8])

In [25]:
# Now, when I change values in arr_slice, the mutations are reflected in the original array arr:
arr_slice[2] = 12345 

In [26]:
arr

array([    0,     1,     2,     3,     4, 12345,     8,     8,     8,     9])

In [27]:
# The “bare” slice [:] will assign to all values in an array
arr_slice[:] = 69 

In [28]:
arr

array([ 0,  1,  2, 69, 69, 69, 69,  8,  8,  9])

In [32]:
# If you want a copy of a slice of an ndarray instead of a view, you will need to explicitly copy the array
arr_copy = arr.copy(); arr_copy

array([ 0,  1,  2, 69, 69, 69, 69,  8,  8,  9])

two-dimensional array indexing

In [43]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]); arr2d 
# think of axis 0 as the “rows” of the array and axis 1 as the “columns”

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
arr2d[1]

array([4, 5, 6])

In [45]:
# individual elements can be accessed recursively using a comma-separated list of indices
arr2d[1][0]

4

In [46]:
# So these are equivalent
arr2d[1,0] 

4

multidimensional arrays indexing

In [52]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 11, 12], [13, 14, 15], [16, 17, 18]]]); arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [56]:
#if you omit later indices, the returned object will be a lower dimensional ndarray consisting of all the data along the higher dimensions
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [57]:
arr3d[0,1,2]

6

#### Indexing with slices

two-dimensional array slicing

In [64]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [66]:
arr2d[:2] # it will slice along axis 0

array([[1, 2, 3],
       [4, 5, 6]])

In [68]:
arr2d[:2,1:] # multiple slices just like multiple indexes
# you always obtain array views of the same number of dimensions

array([[2, 3],
       [5, 6]])

In [69]:
arr2d[:2,2]

array([3, 6])

In [72]:
arr2d[:,1:]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [74]:
arr2d[:,1:] = 0; arr2d # assigning to a slice expression assigns to the whole selection

array([[1, 0, 0],
       [4, 0, 0],
       [7, 0, 0]])

#### Boolean Indexing

In [102]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']); names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'],
      dtype='<U4')

In [103]:
data = np.random.randn(7,4); data

array([[ 0.89675009,  0.02844714,  0.63050086, -0.13706095],
       [ 0.49069422, -0.63018178,  0.70812095, -0.35969909],
       [ 0.1629093 , -1.32223846, -0.37343442,  0.94229482],
       [-1.42633512,  0.13750292,  0.00227705, -0.77212621],
       [-0.46427556, -0.51936543, -0.52429631,  0.2771894 ],
       [-0.98733702,  1.38574436,  0.15097536,  0.21475562],
       [-0.95056121,  0.56685837, -1.36539177, -2.0255866 ]])

In [104]:
names == 'Bob'

array([ True, False, False,  True, False, False, False], dtype=bool)

In [105]:
data[names == 'Bob'] # passing boolean array when indexing 
# Boolean selection will not fail if the boolean array is not the correct length

array([[ 0.89675009,  0.02844714,  0.63050086, -0.13706095],
       [-1.42633512,  0.13750292,  0.00227705, -0.77212621]])

In [106]:
data[names == 'Bob', 2:]

array([[ 0.63050086, -0.13706095],
       [ 0.00227705, -0.77212621]])

In [107]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True], dtype=bool)

In [108]:
data[~(names == 'Bob')]
# condition using ~ operator can be useful when you want to invert a general condition

array([[ 0.49069422, -0.63018178,  0.70812095, -0.35969909],
       [ 0.1629093 , -1.32223846, -0.37343442,  0.94229482],
       [-0.46427556, -0.51936543, -0.52429631,  0.2771894 ],
       [-0.98733702,  1.38574436,  0.15097536,  0.21475562],
       [-0.95056121,  0.56685837, -1.36539177, -2.0255866 ]])

In [109]:
#Selecting two of the three names to combine multiple boolean conditions, use boolean arithmetic operators like & (and) and | (or)
mask = (names=='Bob') | (names=='Will')

In [110]:
mask

array([ True, False,  True,  True,  True, False, False], dtype=bool)

In [111]:
data[mask] # Selecting data from an array by boolean indexing always creates a copy of the data, even if the returned array is unchanged

array([[ 0.89675009,  0.02844714,  0.63050086, -0.13706095],
       [ 0.1629093 , -1.32223846, -0.37343442,  0.94229482],
       [-1.42633512,  0.13750292,  0.00227705, -0.77212621],
       [-0.46427556, -0.51936543, -0.52429631,  0.2771894 ]])

values with boolean

In [112]:
#To set all of the negative values in data to 0 we need only do:
data[data<0] = 0

In [113]:
data

array([[ 0.89675009,  0.02844714,  0.63050086,  0.        ],
       [ 0.49069422,  0.        ,  0.70812095,  0.        ],
       [ 0.1629093 ,  0.        ,  0.        ,  0.94229482],
       [ 0.        ,  0.13750292,  0.00227705,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.2771894 ],
       [ 0.        ,  1.38574436,  0.15097536,  0.21475562],
       [ 0.        ,  0.56685837,  0.        ,  0.        ]])

In [114]:
data[names!='Joe'] = 7

In [115]:
data

array([[ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 0.49069422,  0.        ,  0.70812095,  0.        ],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 0.        ,  1.38574436,  0.15097536,  0.21475562],
       [ 0.        ,  0.56685837,  0.        ,  0.        ]])

#### Fancy Indexing

In [119]:
arr = np.empty((8,4)); arr 

array([[  1.78247646e-312,   6.79038654e-313,   2.14321575e-312,
          6.79038654e-313],
       [  2.29175545e-312,   6.79038654e-313,   2.16443571e-312,
          2.46151512e-312],
       [  2.14321575e-312,   2.33419537e-312,   2.18565567e-312,
          2.46151512e-312],
       [  2.50395503e-312,   6.79038654e-313,   2.05833592e-312,
          2.48273508e-312],
       [  2.44029516e-312,   2.22809558e-312,   6.79038654e-313,
          2.05833592e-312],
       [  2.05833592e-312,   2.46151512e-312,   6.79038654e-313,
          6.79038653e-313],
       [  2.14321575e-312,   2.33419537e-312,   2.14321575e-312,
          6.79038654e-313],
       [  2.33419537e-312,   2.56761491e-312,   2.12199579e-312,
          1.23075756e-312]])

In [120]:
# indexing using integer arrays
for i in range(8):
    arr[i]=i

In [121]:
arr

array([[ 0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.]])

In [122]:
arr[[4, 3, 0, 6]]
# slicing using list or ndarray of integers specifying the desired order

array([[ 4.,  4.,  4.,  4.],
       [ 3.,  3.,  3.,  3.],
       [ 0.,  0.,  0.,  0.],
       [ 6.,  6.,  6.,  6.]])

In [123]:
arr[[-3, -5, -7]]
# negative indices selects rows from the end

array([[ 5.,  5.,  5.,  5.],
       [ 3.,  3.,  3.,  3.],
       [ 1.,  1.,  1.,  1.]])

In [127]:
arr = np.arange(32).reshape((8,4)); arr # Passing multiple index arrays

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [128]:
arr.shape

(8, 4)

In [129]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]
#fancy indexing, unlike slicing, always copies the data into a new array
#the result of fancy indexing is always one-dimensional

array([ 4, 23, 29, 10])

#### Transposing Arrays and Swapping Axes

In [135]:
arr = np.arange(15).reshape((3,5)); arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [137]:
# Transposing with T attribute is a special form of reshaping - 
# returns a view on the underlying data without copying anything.
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

dot product

In [139]:
# handy for doing matrix computations
# for example computing the inner matrix product using np.dot
arr = np.random.randn(6,3); arr

array([[-0.15149663,  1.29845767,  0.49823154],
       [-0.19790273, -0.18532963,  0.54774419],
       [-0.12128569,  1.46976658, -0.68341368],
       [-2.0007399 , -0.81720268,  1.9482018 ],
       [-0.75194916,  0.87545109, -0.29245707],
       [ 1.62313048, -1.67520545,  0.38242508]])

In [140]:
np.dot(arr.T, arr)

array([[ 7.27976715, -2.08065811, -3.15819858],
       [-2.08065811,  8.12110135, -2.94778742],
       [-3.15819858, -2.94778742,  5.04258295]])

swapping axes

In [142]:
arr = np.arange(16).reshape((2,2,4)); arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [144]:
arr.transpose((1, 0, 2)) 
# axes have been reordered with the second axis first, the first axis second, and the last axis unchanged

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [146]:
#transposing with .T is a special case of swapping axes
arr.swapaxes(1,2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])