In [1]:
import numpy as np

Generate some random data

In [6]:
data = np.random.randn(2,3)

In [7]:
data

array([[-1.55836876,  0.90823599,  1.76759503],
       [-1.03671651,  0.01591079, -1.07780967]])

In [8]:
data*10

array([[-15.5836876 ,   9.08235986,  17.67595033],
       [-10.36716514,   0.15910791, -10.77809671]])

In [9]:
data+data

array([[-3.11673752,  1.81647197,  3.53519007],
       [-2.07343303,  0.03182158, -2.15561934]])

In [10]:
data.shape

(2, 3)

In [11]:
data.dtype

dtype('float64')

#### Creating ndarrays

In [13]:
# easiest way to create an array is to use the array function
data1 = [6, 7.5, 8, 0, 1]
arr1= np.array(data1)

In [14]:
arr1

array([ 6. ,  7.5,  8. ,  0. ,  1. ])

In [15]:
# Nested sequences, like a list of equal-length lists, will be converted into a multidimensional array
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)

In [16]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [18]:
# Since data2 was a list of lists, the NumPy array arr2 has two dimensions with shape inferred from the data
arr2.ndim

2

In [19]:
#Unless explicitly specified (more on this later), np.array tries to infer a good data type for the array that it creates
arr2.dtype

dtype('int32')

#### functions for creating new arrays

In [21]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [24]:
np.zeros((3,6))

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [25]:
np.empty((2,3,2)) #In some cases, it may return uninitialized “garbage” values

array([[[ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.]],

       [[ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.]]])

In [26]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

#### Data Types for ndarrays

In [27]:
data3 = [1,2,3]
arr3 = np.array(data3, dtype=np.int64)

In [28]:
arr3

array([1, 2, 3], dtype=int64)

In [29]:
arr3 = np.array(data3, dtype=np.float64)

In [30]:
arr3

array([ 1.,  2.,  3.])

In [31]:
arr3.dtype

dtype('float64')

#### converting or casting array dtype

In [35]:
int_array = arr3.astype(np.int64)

In [36]:
int_array

array([1, 2, 3], dtype=int64)

converting array of strings representing numbers

In [37]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
#numpy.string_ type, as string data in NumPy is fixed size and may truncate input without warning

In [38]:
numeric_strings

array([b'1.25', b'-9.6', b'42'],
      dtype='|S4')

In [39]:
numeric_strings.astype(np.float64)

array([  1.25,  -9.6 ,  42.  ])

using another array’s dtype attribute for casting

In [55]:
int_array = np.arange(6); int_array

array([0, 1, 2, 3, 4, 5])

In [58]:
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64); calibers

array([ 0.22 ,  0.27 ,  0.357,  0.38 ,  0.44 ,  0.5  ])

In [64]:
int_array.astype(calibers.dtype)
#Calling astype always creates a new array (a copy of the data), even if the new dtype is the same as the old dtype.

array([ 0.,  1.,  2.,  3.,  4.,  5.])