In [1]:
import numpy as np

### Universal Functions

#### Fast Element-Wise Array Functions

universal function, or ufunc, is a function that performs element-wise operations on data in ndarrays. These are referred to as unary ufuncs

In [5]:
arr = np.arange(10); arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ])

In [7]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03])

Other functions such as add or maximum, take two arrays (thus, binary ufuncs) and return a single array as the result

In [8]:
x = np.random.randn(8)

In [9]:
y = np.random.randn(8)

In [10]:
x

array([ 0.71037111,  0.13738297, -0.0959372 , -0.26133309, -0.03869915,
       -1.1742842 , -0.17834829, -0.69456612])

In [11]:
y

array([ 1.37232311,  0.51492511,  1.18651245, -0.0947335 , -0.04229009,
       -0.44474825,  0.64371215,  0.40059119])

In [12]:
np.maximum(x, y)

array([ 1.37232311,  0.51492511,  1.18651245, -0.0947335 , -0.03869915,
       -0.44474825,  0.64371215,  0.40059119])

ufunc can return multiple arrays

In [13]:
# modf is example of a vectorized version of the built-in Python divmod; 
# it returns the fractional and integral parts of a floating-point array:
arr = np.random.randn(7)*5

In [14]:
arr

array([ 0.03371103, -3.67494982, -2.9399389 ,  2.42358542, -3.38462923,
       -0.43624553, -7.08491205])

In [15]:
remainder, whole_part = np.modf(arr)

In [16]:
remainder

array([ 0.03371103, -0.67494982, -0.9399389 ,  0.42358542, -0.38462923,
       -0.43624553, -0.08491205])

In [17]:
whole_part

array([ 0., -3., -2.,  2., -3., -0., -7.])

Ufuncs accept an optional out argument that allows them to operate in-place on arrays

In [19]:
arr

array([ 0.03371103, -3.67494982, -2.9399389 ,  2.42358542, -3.38462923,
       -0.43624553, -7.08491205])

In [20]:
np.sqrt(arr)

C:\Users\Gavrilov\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([ 0.18360564,         nan,         nan,  1.55678689,         nan,
               nan,         nan])

In [21]:
np.sqrt(arr, arr)

C:\Users\Gavrilov\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([ 0.18360564,         nan,         nan,  1.55678689,         nan,
               nan,         nan])

In [22]:
arr

array([ 0.18360564,         nan,         nan,  1.55678689,         nan,
               nan,         nan])